// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Popular o banco com o catálogo inicial de modelos/problemas.
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    // Migrations usam a conexão direta (DIRECT_URL, sem pgbouncer).
    // Em runtime, a app usa o adapter pg (DATABASE_URL) no PrismaService.
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL,
  },
});
